variables:
  ANDROID_NDK: $(ANDROID_HOME)\android-ndk-r17c
  ANDROID_BUILD_VERSION: 27
  ANDROID_TOOLS_VERSION: 27.0.3
  GRADLE_OPTS: -Dorg.gradle.daemon=false
  #NDK_TOOLS_URL: https://dl.google.com/android/repository/android-ndk-r17c-windows-x86_64.zip
  JEST_JUNIT_OUTPUT: reports/junit/js-test-results.xml

pool:
  vmImage: 'vs2017-win2016'

steps:
- script: |
    echo ##vso[task.prependpath]$(ANDROID_HOME)\tools\bin
  displayName: 'Add Android tools to path'

- script: |
    sdkmanager "system-images;android-19;google_apis;armeabi-v7a"
    sdkmanager "platforms;android-$(ANDROID_BUILD_VERSION)"
    sdkmanager "build-tools;$(ANDROID_TOOLS_VERSION)"
    sdkmanager "add-ons;addon-google_apis-google-23"
    sdkmanager "extras;android;m2repository"    
  displayName: 'Setup Android SDK'

- task: NodeTool@0
  inputs:
    versionSpec: '8.x'
  displayName: 'Install Node.js'

- script: |
    yarn install
    gradlew.bat RNTester:android:app:assembleRelease
  displayName: 'Build'
  
- script: |
    yarn test-ci-win
  displayName: 'Test'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '$(JEST_JUNIT_OUTPUT)'
  condition: always()
  displayName: 'Publish test results'
